Update CMakeLists.txt
解决找不到libpthread.so.0的问题。
报错信息：
/usr/bin/ld: CMakeFiles/sherpa-offline.dir/offline-recognizer.cc.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status